parameters:
  - name: storageaccount
    type: string

  - name: containername
    type: string

  - name: statefilename
    type: string

  - name: workingdir
    type: string

  - name: backendServiceArm
    type: string

    
stages:
  - stage: stage2
    displayName: terraform init
    jobs:
      - job: terraformInit
        displayName: terraform init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: ${{ parameters.workingdir }}
            backendServiceArm: ${{ parameters.backendServiceArm }}
            backendAzureRmStorageAccountName: ${{ parameters.storageaccount }}
            backendAzureRmContainerName: ${{ parameters.containername }}
            backendAzureRmKey: ${{ parameters.statefilename }}
